### ISSUE TITLE
How to make library work is by doing the following:

### ISSUE THREAD

**Issue by bitbronze** [Hyun-je/pyrplidar#4]
In pylidarserial.py, change the dsrdtr to false:
`dsrdtr=False`

In your code make sure baudrate is changed to 256000 for A3, and that the COM port is correct (on windows), or the corresponding device on linux:
```
lidar = PyRPlidar()
lidar.connect(port="COM3", baudrate=256000, timeout=3) 
lidar.set_motor_pwm(660)
scan_generator = lidar.start_scan_express(3)

for scan in scan_generator():
    scan = vars(scan)
    angle = scan["angle"]
    distance = scan["distance"]
    print("Angle= " + str(angle) + ", Distance= " + str(distance))
```

**Comment by Mytre** [comment]
doing this still gives errors with sync bytes mimsmatched and descriptor mismatch

**Comment by omkger** [comment]
What is your device? Maybe change the bitrate to 115200.

**Comment by Mytre** [comment]
its an a3, it runs on 256000.  I was able to fix this by changing to express scan mode ,  normal scan mode gives me the mismatched bytes and descriptor mismatch too. bbut express scan is giving me the correct numbers.  

For anyone running an A3 , doing this works and lets you run force scan and express scan.

**Comment by bitbronze** [comment]
Express mode 0 is the normal scan. In my experience mode 3 gives the best result overall. I prettied up the original post for future readers.
https://imgur.com/ZFiudfI

**Comment by Mytre** [comment]
Thanks, really informative. I am using right now Express mode 4 which I assume is stability mode on the A3 which fits my needs.  As a side, if you know how to print or call out specific values such as angle, and distance you could write them for future people reading this post.  

I believe using print(scan.angle) would print only the angle.

**Comment by bitbronze** [comment]
Updated the original post. You're welcome :)

**Comment by Mytre** [comment]
Small note here , awesome editing on the first post.

Do you know the units at which the distance is reported? I cannot find what type of unit is and I am assuming it is Cm .  Thanks in advance.

**Comment by bitbronze** [comment]
Distance is in mm (millimetres). Angle is in regular degrees.

**Comment by Mytre** [comment]
Awesome, thank you again , you helped me a lot and surely a lot of others who will see this post later on.

**Comment by Mytre** [comment]
> 
> 
> Distance is in mm (millimetres). Angle is in regular degrees.

Hey, a small question. have you bbeen able to verify which mode is which? Lately express_mode (4) seems to have a low precision.

**Comment by bitbronze** [comment]
Please refer to https://imgur.com/ZFiudfI. The first is 0 last is 4. In my experience 3 works best, then 2, then the rest.

**Comment by Mytre** [comment]
> 
> 
> Please refer to https://imgur.com/ZFiudfI. The first is 0 last is 4. In my experience 3 works best, then 2, then the rest.

Yes, it has the better readings indoors. But I am trying to use the lidar outdoors during daytime.   Following that 4 should be fine for my needs , I will just continue testing. Thank you.
